server:
  port: 18888


spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ssh?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
    #数据源连接池
    type: com.alibaba.druid.pool.DruidDataSource
    #配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j2
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500


  #模板引擎
  freemarker:
    #ftl文件路径
    template-loader-path: classpath:/templates
    # 关闭缓存，及时刷新，上线生产环境需要修改为true
    cache: false
    charset: utf-8
    suffix: .ftl